### ISSUE TITLE
BC Break: Since 2.7.2, assertions no longer behave as documented

### ISSUE THREAD

**Issue by glennschmidt** [laminas/laminas-permissions-acl#12]
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | 2.7.2

#### Summary

According to the documentation, an assertion determines _whether a rule applies_. It doesn't determine whether the rule is an allow rule or a deny rule.

From https://docs.laminas.dev/laminas-permissions-acl/advanced/:

> ...in all other cases (i.e., where a specific role, resource, or privilege is specified for the rule), a failed assertion **results in the rule not applying, and other rules would be used to determine whether access is allowed or denied**.

#### Previous behavior

If a specific 'allow' rule has an assertion that returns false, the rule is skipped, and any other more general rules are applied.

#### Current behavior

If a specific 'allow' rule has an assertion that returns false, it is being treated like a 'deny' rule.

#### How to reproduce

```PHP
use Laminas\Permissions\Acl\Acl;
use Laminas\Permissions\Acl\Assertion\CallbackAssertion;

$acl = new Acl();
$acl->addRole('user');
$acl->addResource('asset');

$acl->allow('user', 'asset', 'read', new CallbackAssertion(
    fn ($acl, $role, $res, $priv) => false
));

$acl->allow('user', null, null);

var_dump($acl->isAllowed('user', 'asset', 'read'));
```

This code prints 'true' with version 2.7.1, but 'false' with version 2.7.2.

**Comment by MrHash** [comment]
Same problem here.

**Comment by MrHash** [comment]
Any feedback on this change in behaviour @weierophinney? thanks

**Comment by criterion9** [comment]
I just encountered this issue as well. In my case this meant a user was denied access by 1 rule even though they should have been allowed by another rule. Any thoughts on if this will be the behavior going forward or if this is a bug?

**Comment by Ocramius** [comment]
Can we pinpoint this to a specific line/diff with a regression (unit) test please? :)

**Comment by criterion9** [comment]
Looking at the diff from the 2.7.1->2.7.2 commit it seems that the section around line ~1022 used to return empty instead of allow or deny for an assert that didn't pass.
```
       if (null === $rule['assert'] || $assertionValue) {
            return $rule['type'];
        } elseif (null !== $resource || null !== $role || null !== $privilege) {
            return;	
        } elseif (self::TYPE_ALLOW === $rule['type']) {	
            return self::TYPE_DENY;	
        }
       return self::TYPE_ALLOW;
```
The new code always returns allow or deny:
```
 // Was a custom assertion supplied? Use it to retrieve the rule type.
        if ($rule['assert']) {
	            return $this->getRuleTypeFromAssertion($rule['assert'], $rule['type'], $role, $resource);
	        }
       // Return the type supplied with the rule.
        return $rule['type'];
```

I haven't contributed to these libraries before but would be willing to take a stab at a unit test if there were some clear "getting started" type instructions someone could point me to.

**Comment by Sandldan** [comment]
I ran into this issue as well, created a test and tried to come up with a fix but reverted to `2.7.1` for now.

This BC break got introduced when fixing this issue https://github.com/laminas/laminas-permissions-acl/issues/2

[Specifically this path got removed](https://github.com/laminas/laminas-permissions-acl/blob/624567fe376a70e0bfb5aa8217d5afa13b9d6e61/src/Acl.php#L1033):

```
} elseif (null !== $resource || null !== $role || null !== $privilege) {
    return;
}
```

From my poking around these two issues seems somewhat at odds with each other and I'm not sure how to resolve them in a good way :confused:

**Comment by boesing** [comment]
> This BC break got introduced when fixing this issue #2
> 
> [Specifically this path got removed](https://github.com/laminas/laminas-permissions-acl/blob/624567fe376a70e0bfb5aa8217d5afa13b9d6e61/src/Acl.php#L1033):
> 
> ```
> } elseif (null !== $resource || null !== $role || null !== $privilege) {
>     return;
> }
> ```

TBH: I am not 100% sure if this is a bug/bc break or the mentioned change was a bugfix.

It is explicitly configured, that the `user` has **no** `read` privilege on `asset` resources.
_(referring to the issue authors example in the initial post)_

Why would you expect `true` in this case?
Do I miss something?

/cc @Ocramius @weierophinney @michalbundyra

**Comment by MrHash** [comment]
Changing long standing behaviour in this way is not a serendipitous bug
fix. Logically, access control on a resource which is not under control
should pass and is the expected behaviour as defined in the documentation.

**Comment by boesing** [comment]
> [...] and is the expected behaviour as defined in the documentation.

Could you point me to that documentation? I dont want to argue about this, I just want to understand the issue better as I dont use this package at all. 

----

And just to understand, you expect that if `allow` is being called without any specifications, **any** rule has to pass, right?
Regardless of what is explicitly disallowed.

**Comment by MrHash** [comment]
The link is in the issue description.

**Comment by boesing** [comment]
@MrHash If I understand the documentation correct, it states that it needs an assertion which explicitly allows permission for **all** roles and **all** privileges.

The example code mentioned in the issue description explicitly revokes grants for `user` `read` on `asset` resource. 
If you want to allow anything to the `user`, why would you revoke access in the first place?

**Comment by MrHash** [comment]
Aside from the fact that you say you don't use this package, and that you don't want to argue about it, and that this is obviously the wrong way to introduce a behavioural change in the code, with these breaking changes there is now no way to correctly chain assertions when a prior one fails.

**Comment by boesing** [comment]
>  [...] and that this is obviously the wrong way to introduce a behavioural change in the code

Thats where we agree. 
Its just a tough change as I actually dont see a way of re-implementing the behavior without having failing tests and due to the lack of knowledge, I've just added a failing unit test in #18 for the moment.

**Comment by MrHash** [comment]
Thanks for following up, i'm sure we can work out a fix.

**Comment by criterion9** [comment]
I think the fix for issue 2 inadvertently made BC changes by returning explicit opposite of the rule on a failing assertion. I think the intention of issue where the BC fix was implemented was to return results quickly which is usually a good thing. However, in this case, by explicitly returning the opposite of the privilege the intention of rulesets with fallback/flowthrough are prevented.

**Comment by PowerKiKi** [comment]
I stumbled upon the same root issue, although my use-case is slightly more complex, since it involves role multiple inheritance. If a `super-user` inherit from two other roles, then the order of declaration of the inheritance incorrectly matter since 2.7.2. This was not the case with 2.7.1.

That makes working with inheritance extremely brittle, since changing order, or adding/removing privileges anywhere in the inheritance chain might incorrectly have side effect for other roles in an unexpected way.

My reproduction case below is a role that is always denied, a role that is always allowed and a `super-user` that combine both of those. In all variants of the `super-user` I expect that the privileges are the union of all allowed privileges of inherited roles. Meaning that `super-user` is always allowed. However this is incorrectly no longer the case since 2.7.2.

```php
<?php

require 'vendor/autoload.php';

use Laminas\Permissions\Acl\Acl;
use Laminas\Permissions\Acl\Assertion\CallbackAssertion;

$acl = new Acl();
$acl->addRole('user-deny');
$acl->addRole('user-allow');
$acl->addRole('super-user1', ['user-deny', 'user-allow']);
$acl->addRole('super-user2', ['user-allow', 'user-deny']);
$acl->addResource('asset');

$acl->allow('user-deny', 'asset', 'read', new CallbackAssertion(fn () => false));
$acl->allow('user-allow', 'asset', 'read', new CallbackAssertion(fn () => true));

$roles = array_combine($acl->getRoles(), $acl->getRoles());
$result = array_map(fn ($role) => $acl->isAllowed($role, 'asset', 'read'), $roles);
var_dump($result);
```

# Expected result

As seen in 2.7.1:

```
array(4) {
  'user-deny' =>
  bool(false)
  'user-allow' =>
  bool(true)
  'super-user1' =>
  bool(true)
  'super-user2' =>
  bool(true)
}
```

# Actual result

Since 2.7.2, `super-user2` is incorrectly denied the privilege
```
array(4) {
  'user-deny' =>
  bool(false)
  'user-allow' =>
  bool(true)
  'super-user1' =>
  bool(true)
  'super-user2' =>
  bool(false)
}
```

@weierophinney, since you authored the [problematic commit](https://github.com/laminas/laminas-permissions-acl/commit/54289a1e1a3950b767f8bde13d75cac61e87a259), would you have any opinions to share with us here ?

**Comment by froschdesign** [comment]
@PowerKiKi 
> @weierophinney, since you authored the [problematic commit](https://github.com/laminas/laminas-permissions-acl/commit/54289a1e1a3950b767f8bde13d75cac61e87a259), would you have any opinions to share with us here ?

He has created thousands more commits in the meantime, so don't wait and create a pull request with your use case as test and add a fix.

Thanks in advance! 👍

**Comment by PowerKiKi** [comment]
https://github.com/laminas/laminas-permissions-acl/pull/23 should solve this.
